name: core
description: Core domain primitives, functional result, DI, logger, and hardware adapters for Zaynahs Ecosystem.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.11.0

dev_dependencies:
  test: ^1.24.0
